apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    # Source 1: MinIO Official Helm chart
    - repoURL: https://charts.min.io
      chart: minio
      targetRevision: 5.4.0
      helm:
        valueFiles:
          - $values/values/minio/values.yaml

    # Source 2: Git repo chứa values file
    - repoURL: https://github.com/Thahn-Tam/redis.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: minio

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true