apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    # Source 1: Helm chart từ Bitnami
    - repoURL: https://charts.bitnami.com/bitnami
      chart: redis
      targetRevision: 20.6.0
      helm:
        valueFiles:
          - $values/values/redis/values.yaml

    # Source 2: Git repo chứa values file
    - repoURL: https://github.com/Thahn-Tam/redis.git  # Thay bằng repo của bạn
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: redis

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
